install:
  - choco install gitversion.portable -y
  - choco install gitlink -y

assembly_info:
  patch: false

platform:
  - Any CPU

configuration:
  - Release

os: 
- Visual Studio 2015

build_script:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: nuget restore src\Specify.sln
  - cmd: gitversion /l console /output buildserver /updateAssemblyInfo
  
  - cmd: msbuild src\Specify.sln "/p:Configuration=%CONFIGURATION%;Platform=%PLATFORM%"

  - cmd: ECHO GitLink . -u https://github.com/mwhelan -c %CONFIGURATION% -ignore Specify.Examples,Specify.IntegrationTests,Specify.IntegrationTests.App,Specify.Tests,ContosoUniversity,ContosoUniversity.AcceptanceTests,ContosoUniversity.FunctionalTests,ContosoUniversity.SubcutaneousTests,ContosoUniversity.UnitTests
  - cmd: GitLink . -u https://github.com/mwhelan -c %CONFIGURATION% -ignore Specify.Examples,Specify.IntegrationTests,Specify.IntegrationTests.App,Specify.Tests,ContosoUniversity,ContosoUniversity.AcceptanceTests,ContosoUniversity.FunctionalTests,ContosoUniversity.SubcutaneousTests,ContosoUniversity.UnitTests

  - cmd: ECHO nuget pack nuget\Specify.nuspec -version "%GitVersion_NuGetVersion%" -prop "configuration=%CONFIGURATION%"
  - cmd: nuget pack nuget\Specify.nuspec -version "%GitVersion_NuGetVersion%" -prop "configuration=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Specify.%GitVersion_NuGetVersion%.nupkg"

  - cmd: ECHO nuget pack nuget\Specify.Autofac.nuspec -version "%GitVersion_NuGetVersion%" -prop "configuration=%CONFIGURATION%"
  - cmd: nuget pack nuget\Specify.Autofac.nuspec -version "%GitVersion_NuGetVersion%" -prop "configuration=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Specify.Autofac.%GitVersion_NuGetVersion%.nupkg"

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  
test:
  assemblies:
  - Specify.Tests.dll
  - Specify.IntegrationTests.dll  